name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: poetry install
      - run: poetry build
      - run: python3 -m pip install --user dist/*.whl
      - run: poetry run flake8 brain_games
     
